### ISSUE TITLE
How to export metrics on a different port

### ISSUE THREAD

**Issue by rajataneja101** [trallnag/prometheus-fastapi-instrumentator#10]
Is it possible to export metrics on a different port instead of using application port?

**Comment by trallnag** [comment]
If you want to do that don't use the provided `expose` method. Just instrument the API and expose the metrics endpoint yourself for example like this:

```
from prometheus_client import start_http_server

start_http_server(8000)
```

**Comment by rajataneja101** [comment]
Thanks 👍

**Comment by rajataneja101** [comment]
So default port will also work alongwith this port?

**Comment by trallnag** [comment]
Not 100 % sure what you mean, but I would say yes 😄

**Comment by VMAtm** [comment]
Hi, sorry for bringing this old issue up.
Is there any example of `start_http_server` on a dedicated port?
I'm using FastAPI with uvicorn, and I want to export the metrics on a different port. I call `start_http_server`, but I never get any answer from that endpoint.
Is there any complete example of how this can be done?

**Comment by trallnag** [comment]
Hi @VMAtm, I can't reproduce your issue. Here is the example I tried: https://github.com/trallnag/prometheus-fastapi-instrumentator/tree/example-different-port/devel/examples/metrics-diff-port-uvicorn

**Comment by VMAtm** [comment]
Thank you @trallnag 
I'll check on my side, thank you for the fast example!

**Comment by VMAtm** [comment]
Hi, sorry that this took so long. Your example is perfect, thank you, this worked

**Comment by trallnag** [comment]
Happy to hear that

**Comment by lkiii** [comment]
> Hi @VMAtm, I can't reproduce your issue. Here is the example I tried: https://github.com/trallnag/prometheus-fastapi-instrumentator/tree/example-different-port/devel/examples/metrics-diff-port-uvicorn

This is no longer present. I am also struggling to get this working

**Comment by gpkc** [comment]
@lkiii It's still available: https://github.com/trallnag/prometheus-fastapi-instrumentator/blob/master/devel/examples/metrics-diff-port-uvicorn/main.py

Just search for `start_http_server` in the search bar.

**Comment by lkiii** [comment]
Thank you for the reply @gpkc . I was able to figure it out.

Sharing it if someone else will get here looking for answers
```python


def start_metrics_server():
    logger.info(f"Starting Prometheus server on port {settings.PROMETHEUS_PORT}")
    start_http_server(port=settings.PROMETHEUS_PORT)


def metrics_setup(app: FastAPI):
    Instrumentator().instrument(app)
    metrics_thread = threading.Thread(target=start_metrics_server, daemon=True)
    metrics_thread.start()

app = FastAPI(...)
FastAPIInstrumentor.instrument_app(app)
metrics_setup(app)
```
