### ISSUE TITLE
How to prefix metric names? 

### ISSUE THREAD

**Issue by codyflynnNC** [trallnag/prometheus-fastapi-instrumentator#11]
In something like Dogstatsd you can prefix your metrics using the namespace argument. 

` statsd = DogStatsd(host=statd_host, port=statd_port, namespace="your_apps_name")` 

this way in prometheus the metrics can be separated by app. Is something like this possible here?

**Comment by codyflynnNC** [comment]
So after looking through the source code, it seems the default instrument function:

`        if len(self.instrumentations) == 0:
            self.instrumentations.append(metrics.default())
`

while the instantiation of the class does not take in instrumentation args. I'd propose a change to the instantation of the class to take in the namepsace arg, then pass that into  `
        if len(self.instrumentations) == 0:
            self.instrumentations.append(metrics.default(metric_namespace=self.metric_namespace))`

if this makes sense im happy to create a PR

**Comment by trallnag** [comment]
Hey @codyflynnNC, I'd prefer not to include a `metric_namespace` attribute in the `instrumentation` module. The idea is to separate the actual definition of the metrics and the instrumentation that gets data from FastAPI. If we add `metric_namespace` a user would assume that it will be respected by all functions you can find in the `metrics` module which is not the case.

If you want to set the namespace go for:

```
instrumentator.add(metrics.default(metric_namespace="name_space")
```

Or add your own function instead which gives you more control.

**Comment by codyflynnNC** [comment]
Thanks for the quick response. that works perfectly. I'll close this issue.
