### ISSUE TITLE
New metric: number of requests in progress

### ISSUE THREAD

**Issue by jpslopes** [trallnag/prometheus-fastapi-instrumentator#13]
Hello, do you have plans to add more metrics in the future? It would be great to have a metric that shows the number of requests in progress.

Thanks!

**Comment by trallnag** [comment]
Hey @jpslopes, thanks for the notice. Indeed it is currently not possible to do this even hooking in your own instrumentation as described here <https://github.com/trallnag/prometheus-fastapi-instrumentator#creating-new-metrics>. I'll come up with a solution and implement it in the next few days once I get to it

**Comment by trallnag** [comment]
A metric for requests in progress is now implemented with version 5.4.0 (see [here](https://github.com/trallnag/prometheus-fastapi-instrumentator/releases/tag/releases%2F5.4.0) for release notes). To enable the metric set the `should_instrument_requests_inprogress` flag. You can override the default metric name `http_requests_inprogress` with `inprogress_name`. By default the metric has no labels. To add `handler` and `method` set `inprogress_labels` to `True`.

```python
Instrumentator(should_instrument_requests_inprogress=True)
```

**Comment by jpslopes** [comment]
Thanks!
