### ISSUE TITLE
Process Metrics unavailable to the MultiProcess CollectorRegistry

### ISSUE THREAD

**Issue by sarasensible** [trallnag/prometheus-fastapi-instrumentator#138]
We are looking to get the process metrics such as `process_resident_memory_bytes` and `process_cpu_seconds_total` added to our FastAPI metrics endpoint.  We are using the MultiProcessCollector which invokes CollectorRegistry and it looks like this doesn't allow for adding the ProcessCollector which generates those metrics.  If for testing purposes I manually edit `instrumentation.py` and register PROCESSCOLLECTOR I can see the desired metrics in the output.  

Is there some overriding reason that PROCESSCOLLECTOR is unavailable to the MultiProcessCollector?  Is there some other way to achieve including the process metrics in the output?  If not, we can investigate submitting a PR that allows optional additional collectors to be passed into the expose method.

**Comment by trallnag** [comment]
Reading the documentation https://github.com/prometheus/client_python#multiprocess-mode-eg-gunicorn from my understanding ProcessCollector is not support with multi process mode.
