### ISSUE TITLE
Unexpected print in Middleware

### ISSUE THREAD

**Issue by DenysMoskalenko** [trallnag/prometheus-fastapi-instrumentator#151]
Hello)
I found the print in library code: https://github.com/trallnag/prometheus-fastapi-instrumentator/blob/673b922e97a4e943a0e4d23db7767015e4c751dd/prometheus_fastapi_instrumentator/middleware.py#L80
Can you pls remove it or allow some customization of this behavior?)

**Comment by trallnag** [comment]
Fixed in #157. Will be released soon(tm)
