### ISSUE TITLE
Print in middleware component

### ISSUE THREAD

**Issue by mattzque** [trallnag/prometheus-fastapi-instrumentator#156]
In version 5.8.2 the PrometheusInstrumentatorMiddleware prints to stdout on every request, this should not be in the release:

https://github.com/trallnag/prometheus-fastapi-instrumentator/blob/master/prometheus_fastapi_instrumentator/middleware.py#L80

Workaround: Downgrade to 5.8.1

**Comment by pawamoy** [comment]
Hahahaha I was going crazy, looking for print statements in my own code, then in every involved library (uvicorn, starlette, fastapi, ...) 🤣

**Comment by nikitunkun** [comment]
I went through all the code looking for this print...
Waiting for a fix 🙃

**Comment by Jason-CKY** [comment]
Hope this is fixed soon

**Comment by trallnag** [comment]
Fixed in #157. Will be released soon(tm)
