### ISSUE TITLE
Adding FastAPI tags to metrics route

### ISSUE THREAD

**Issue by chisaipete** [trallnag/prometheus-fastapi-instrumentator#17]
Is there a way to customize where the metrics route is tagged in the generated FastAPI docs?  I'm using [tags](https://fastapi.tiangolo.com/tutorial/path-operation-configuration/#tags) to group routes, but my instrumented routes ('/metrics') always ends up in "default".

**Comment by trallnag** [comment]
Hey @chisaipete, this is currently not possible and I must say that the tags feature is new to me. It should be pretty easy to add (just another parameter 😄), but in the mean time you can skip the `expose()` and add the endpoint yourself. Here is how it could look like:

```python
from prometheus_client import REGISTRY, CONTENT_TYPE_LATEST
from starlette.requests import Request  # or import it from FastAPI
from starlette.responses import Response  # or import it from FastAPI


@app.get("/metrics", tags=["whatever"])
def metrics(request: Request):
    resp = Response(content=generate_latest(REGISTRY))
    resp.headers["Content-Type"] = CONTENT_TYPE_LATEST
    return resp
```

I think I'll add support for tags over the next weekends when I find the time

**Comment by chisaipete** [comment]
Great! It's not a huge blocker right now, just an annoyance. Thanks for the workaround, looking forward to the enhancement!

**Comment by Kludex** [comment]
That was fast.

**Comment by trallnag** [comment]
Okay I added the passthrough of tags parameter to the `expose()` in version 5.6.0 [here](https://github.com/trallnag/prometheus-fastapi-instrumentator/releases/tag/releases%2F5.6.0). Just 2 lines so I did not want to wait. I think I will refactor it to also pass through arbitrary args / kwargs (in addition to the hardcoded ones) once I have more time.

@Kludex, he caught me right before going to bed, so good timing

**Comment by chisaipete** [comment]
Oh wow! Let me confirm this is working.

**Comment by chisaipete** [comment]
Umm, I'm not sure this is out in PyPi yet, I tried to check for package updates but I'm still seeing 5.5.1

`TypeError: expose() got an unexpected keyword argument 'tags'`

**Comment by chisaipete** [comment]
Nevermind, that was a PyCharm weirdness, I was able to explicitly set the version to 5.6.0 and pull the new version.  Works great, thanks!
