### ISSUE TITLE
Passthrough arbitrary args / kwargs from expose() to FastAPI decorator

### ISSUE THREAD

**Issue by trallnag** [trallnag/prometheus-fastapi-instrumentator#18]
This way the parameters don't have to cover every possible use case

**Comment by Kludex** [comment]
You'll lose the autocomplete duck type, u sure?

**Comment by trallnag** [comment]
Yes you are right, that is a good point. Thanks for the hint. Maybe I'll just add it as an addition to "hard coded" parameters so in case something not covered comes up you can fall back to that

**Comment by trallnag** [comment]
Implemented in `5.7.0` but of course not the recommended way to go, just a fallback
