### ISSUE TITLE
HTTPStatus.NOT_FOUND results in status "Hxx" when grouping (with fix)

### ISSUE THREAD

**Issue by Leem0sh** [trallnag/prometheus-fastapi-instrumentator#190]
Hello, 

just noticed a bug where any "non-numeric" status code for example 

```py
from http import HTTPStatus
from starlette.responses import JSONResponse


@router.post(...)
def f():
    ...
    return JSONResponse(status_code=HTTPStatus.NOT_FOUND, detail="Item not found")
```

results in 

```
http_requests_total{handler="/myhandler",method="POST",status="Hxx"} 3.0
```

Easy fix in my code is to do `int(HTTPStatus.NOT_FOUND)`.

Or you can probably fix it in https://github.com/trallnag/prometheus-fastapi-instrumentator/blob/master/src/prometheus_fastapi_instrumentator/middleware.py#L117

```
status = str(int(status))[0] + "xx"
```
?

**Comment by nikstuckenbrock** [comment]
I've created the PR #192 to fix this issue.
