### ISSUE TITLE
How to add metrics

### ISSUE THREAD

**Issue by pawamoy** [trallnag/prometheus-fastapi-instrumentator#2]
Hello! Thanks for the projet 🙂 

I read the README and I'm left wondering how I can add metrics to the already defined ones. Is this even possible yet? For example, I'd like to add the average transfered data size per request/response. How would I add this into the instrumentator?

**Comment by pawamoy** [comment]
Thanks for the quick answer!

> Do you want the transfered data metric just for a few specific endpoints or all endpoints transparently?

Depends! It was just an example 🙂 Could be both.

Oh yes, it seems `prometheus_flask_exporter` allows to do what I'm looking for.

So I would say: don't hardcode it! Instead, provide a way for users to add their own custom, exported metrics.

**Comment by trallnag** [comment]
@pawamoy you can now select from a few already existing instrumentations or add your own. Check the updated `README.md` for more info.

Recording size of requests / responses:

```python
instrumentator.add(
    metrics.http_request_duration_seconds(buckets=(1, 2, 3,))
).add(
    metrics.http_request_content_length_bytes(should_drop_handler=True)
).add(
    metrics.http_response_content_length_bytes(should_drop_handler=True)
)
```

Or creating your own:

```python
def http_requested_languages_total() -> Callable[[Info], None]:
    METRIC = Counter(
        "http_requested_languages_total", 
        "Number of times a certain language has been requested.", 
        labelnames=("langs",)
    )

    def instrumentation(info: Info) -> None:
        langs = set()
        lang_str = info.request.headers["Accept-Language"]
        for element in lang_str.split(",")
            element = element.split(";")[0].strip().lower()
            langs.add(element)
        for language in langs:
            METRIC.labels(language).inc()

    return instrumentation

instrumentator.add(http_requested_languages_total())
```
