### ISSUE TITLE
CPU and MEM metrics not available with multiworkers 

### ISSUE THREAD

**Issue by Pazzeo** [trallnag/prometheus-fastapi-instrumentator#207]
Hi,

Following the issue #50, I was able to configure the right metrics when multi workers are in use in the system.
However, I'm not able to have the metrics for CPU and memory. 
Do you know why? 

Thanks
Matteo

**Comment by trallnag** [comment]
This is unrelated to trallnag/prometheus-fastapi-instrumentator. The official Prometheus client library for Python does not include these metrics when multi process mode is enabled.

See: https://github.com/prometheus/client_python#multiprocess-mode-eg-gunicorn
