### ISSUE TITLE
Example for "manually" pushing a metric

### ISSUE THREAD

**Issue by trondhindenes** [trallnag/prometheus-fastapi-instrumentator#21]
I'd love to see an example of how to "manually" submit a metric, something like:

pseudocode:

```python
@app.get('/super-route')
async def super-thing():
     business_result = await call_some_business_logic()
     metrics.push(business_result.count)
```
it's difficult to see how to "interact" with the metrics dynamically in code without going through the request/response object.

**Comment by trallnag** [comment]
Hey @trondhindenes, you can just use the Prometheus client library for that. Create a metric and increment it. I can post an example later.

This package is really just for getting metric from your FastAPI (how many requests, duration etc) and not a generic instrumentation library. Under the hood it does nothing more than creating a few a Prometheus metric and extractive relevant label data from requests and responses.

**Comment by cbartz** [comment]
@trallnag You should mention in the documentation that one can use the Prometheus client library aside from your library, and that those metrics will be automatically exposed. [starlette_exporter](https://github.com/stephenhillier/starlette_exporter#custom-metrics) does mention this.

**Comment by trondhindenes** [comment]
thanks both - that makes total sense but mentioning in the docs would probably be valuable

**Comment by trallnag** [comment]
I added a info to the `README.md`
