### ISSUE TITLE
_created metrics are not created in multi-process mode

### ISSUE THREAD

**Issue by zdets** [trallnag/prometheus-fastapi-instrumentator#232]
Issue since version 5.10.0.

**Comment by trallnag** [comment]
Hi @zdets, bad news, this is actually not supported by the official Prometheus client library that is used by this package. In previous versions of this package the `/metrics` endpoint in multi process mode was implemented incorrectly. So while these "created" metrics were available, there were most likely not correct.

Please see this example highlighting the behavior: https://github.com/trallnag/prometheus-fastapi-instrumentator/tree/master/devel/examples/prom-multi-proc-gunicorn

Also see the documentation: https://github.com/prometheus/client_python#multiprocess-mode-eg-gunicorn

> To handle this the client library can be put in multiprocess mode. This comes with a number of limitations:
>
> - Registries can not be used as normal, all instantiated metrics are exported
> - Registering metrics to a registry later used by a MultiProcessCollector may cause duplicate metrics to be exported
> - **Custom collectors do not work (e.g. cpu and memory metrics)**
> - **Info and Enum metrics do not work**
> - The pushgateway cannot be used
> - Gauges cannot use the pid label
> - Exemplars are not supported

Not sure if there is a workaround.

**Comment by zdets** [comment]
Thanks for the clarification.
