### ISSUE TITLE
FastAPI app with many routers

### ISSUE THREAD

**Issue by bhaktatejas922** [trallnag/prometheus-fastapi-instrumentator#274]
Hey, 

Trying to use this in a FastAPI app with many routers

    app.include_router(router)
    app.on_event("startup")(setup_caching)
    app.on_event("shutdown")(Engine.teardown)
    Instrumentator().instrument(app).expose(app, endpoint="/api/v1/metrics")

It only seems to get metrics at the root, are openapi.json and /docs and nothing else

**Comment by satishsbhat** [comment]
@bhaktatejas922 how did you resolved this ?

**Comment by bhaktatejas922** [comment]
add it before you add the router
`    app = FastAPI()

    origins = ["*"]

    @app.get("/health")
    def get_health():
        return {"status": "OK"}

    app.add_middleware(
        CORSMiddleware, allow_origins=origins, allow_credentials=True, allow_methods=["*"], allow_headers=["*"]
    )

    Instrumentator().instrument(app).expose(app, endpoint="/api/v1/metrics")
    app.include_router(router)`

**Comment by satishsbhat** [comment]
@bhaktatejas922 Thanks that works !
