### ISSUE TITLE
Body not present on instrumentation info.response object

### ISSUE THREAD

**Issue by roger-domenech-aguilera** [trallnag/prometheus-fastapi-instrumentator#76]
Hi!

When calling the instrumentation function inside my custom metric, the response attribute of the info parameter does not have body.

```
def whatever() -> Callable[[Info], None]:
    metric = Gauge("whatever",
                   "This metric tracks whatever api usage.")

    def instrumentation(info: Info) -> None:
        request = info.request
        response = info.response
        body = response.body

    return instrumentation
```

**AttributeError: 'StreamingResponse' object has no attribute 'body'**

Is there a way to circumvent this issue or maybe I'm doing sth wrong!

Thank you all in advance!

**Comment by espositoandrea** [comment]
Hi! I've got the same issue here!
As a workaround I'm temporarily adding a custom header `X-[foo]` to hold the value that I would access from the body: don't know if that may help you for the time being 😄.

**Comment by abb4s** [comment]
same issue!!
```
def http_requested_languages_total():
    METRIC = Counter(
        "http_requested_languages_total", 
        "Number of times a certain language has been requested.", 
        labelnames=("spell_status",)
    )

    def instrumentation(info: Info) -> None:


        print(info.request)
        print(str(info.response.body_iterator))
        print(info.response.headers)
        # x = loads(info.response.body_iterator)["spell_status"]
        METRIC.labels(2).inc()

    return instrumentation
```
I want to create a new metric but the info.resonse object is a StreamResponse . how can i convert it to dict?

**Comment by tobikang** [comment]
Same issue.

**Comment by AbhishekBose** [comment]
Same issue. Body seems to be empty when I print it

**Comment by oysteins10** [comment]
Hey! I took a look in the prometheus middleware where it constructs the Info object. The middleware only grabs the headers and status code and constructs an empty bodied response object. 
This snippet right here in the `PrometheusInstrumentatorMiddleware.__call__` func in `middleware.py` (line 120):
````python
...
response = Response(headers=Headers(raw=headers), status_code=status_code)  # type: ignore

info = metrics.Info(
             request=request,
             response=response,
             method=request.method,
             modified_handler=handler,
             modified_status=status,
             modified_duration=duration,
        )
...
````
I dont know why the authors did not include the response body as I know the the [ FastApi docs middleware docs](https://fastapi.tiangolo.com/tutorial/middleware/#create-a-middleware) uses Starlettes `BaseHTTPMiddleware` to grab the response object. Anyway, it's clear that the response body is not intended to be included. I also need to grab some metrics from the response body and will probably create my own implementation with a middleware using `BaseHTTPMiddleware`

**Comment by msemelman-vrff** [comment]
Hi I linked a PR trying to solve this issue. We are interested in getting this through. Can someone review please?

**Comment by bbeattie-phxlabs** [comment]
Introduction of body data in this way kills performance for large FileResponse responses.

**Comment by trallnag** [comment]
There is a bug with this implementation. See issue #236.

It only works if response data is being streamed.

**Comment by trallnag** [comment]
FYI: There is a new release with a breaking change regarding this feature.

https://github.com/trallnag/prometheus-fastapi-instrumentator/releases/tag/v6.0.0
