### ISSUE TITLE
Project still uses prometheus_multiproc_dir environment variable in lower-case

### ISSUE THREAD

**Issue by neilferreira** [trallnag/prometheus-fastapi-instrumentator#89]
To remain consistent with the Prometheus Python client it would be great if the uppercase version of this environment variable is used, as this is likely what people (like myself) would be trying to use based on the Prometheus documentation.

As per https://github.com/prometheus/client_python/releases/tag/v0.10.0

> [CHANGE] The prometheus_multiproc_dir environment variable is deprecated in favor of PROMETHEUS_MULTIPROC_DIR. #624 - https://github.com/prometheus/client_python/pull/624

The lowercase version is still used in https://github.com/trallnag/prometheus-fastapi-instrumentator/blob/45d0ba1d03c565f2caca807b7df813e434c90ec8/prometheus_fastapi_instrumentator/instrumentation.py#L257

**Comment by trallnag** [comment]
Fixed in #42 / #217
